---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: alertmanager-oauth2-secrets
  namespace: prometheus-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  templates:
    cookie-secret: '{{ "{{" }} cookie {{ "}}" }}'
    client-id: alertmanager-oauth2
    client-secret: COhRsMzr1t0RK2juK4yp4gJwA6wNtfAR2eTiqqoR7qk=
  destination_name: oauth2-alertmanager-oauth2-proxy
  destination_type: Secret
  values:
    - name: cookie
      source_name: password-oauth2-cookie-from-prometheus-system
      source_type: Secret
      source_key: password
---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: alertmanager-oauth2-redis-password
  namespace: prometheus-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  templates:
    redis-password: '{{ "{{" }} password {{ "}}" }}'
  destination_name: oauth2-alertmanager-redis
  destination_type: Secret
  values:
    - name: password
      source_name: password-oauth2-redis-from-prometheus-system
      source_type: Secret
      source_key: password
