domain: dev.exphot.pl
persistent:
  nfs:
    size: 15Gi
metallb:
  pools: []
#    - name: default
#      addresses:
#        - 192.168.8.100-192.168.8.150
#      protocol: layer2

cloudflare:
  proxied: true

passwordGenerator:
  version: v1.2.0
  image:
    tag:
templateRenderer:
  version: v1.3.0
  image:
    tag:

exphostConfigurator:
  version: v1.4.0
  image:
    tag:
