domain: dev.example.com
persistent:
  nfs:
    size: 15Gi
metallb:
  pools: []
#    - name: default
#      addresses:
#        - 192.168.8.100-192.168.8.150
#      protocol: layer2

cloudflare:
  proxied: true

passwordGenerator:
  version: v1.2.0
  image:
    tag:
templateRenderer:
  version: v2.0.0
  image:
    tag:

exphostConfigurator:
  version: v1.5.0
  image:
    tag:

config:
  k8sAdminGroup: oidc:k8s-admins
  dex:
    ldap:
      host: openldap.tenant-exphost-services.svc.cluster.local:389
      password:
        secretName: password-password-dex-from-tenant-exphost-services
        key: password
    staticClients:
      - id: kubernetes
        redirectURIs:
        - 'https://auth.{{ .Values.domain }}/callback'
        name: 'Kubernetes'
        secret: GiQBxaKyVNsNkWshSzuNN8Xa6qnbZLYt
      - id: argo
        redirectURIs:
        - 'https://argocd.{{ .Values.domain }}/auth/callback'
        name: 'ArgoCD'
        secret: nY4pHGFH0dXKARUWwsxh1Q==
      - id: gitlab
        redirectURIs:
        - 'https://gitlab.{{ .Values.domain }}/users/auth/openid_connect/callback'
        - 'https://gitlab.{{ .Values.domain }}/users/auth/exphost/callback'
        name: 'GitLab'
        secret: 7t7qSU17QwzP80s5NYqV4/JTKl8XYyQ+iyrMpslteXo=
      - id: grafana
        redirectURIs:
        - 'https://grafana.{{ .Values.domain }}/login/generic_oauth'
        name: 'Grafana'
        secret: yipcAxlvSLPFgpU+FN+SynW5fAbSQqeG2zTJ/4ioTKU=
  alertmanager:
    globalMail: ~
#      to: mail@example.com
#      from: mail2@example.com
#      smarthost: ~
#      authUsername: ~
#      authPassword:
#        secretName: ~
#        keyName: ~
