---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: longhorn-backup-credentials-access-key
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  template: |
    {{ "{{" }} AWS_ACCESS_KEY_ID {{ "}}" }}
  destination_name: longhorn-backup-credentials
  destination_key: AWS_ACCESS_KEY_ID
  destination_type: Secret
  values:
    - name: AWS_ACCESS_KEY_ID
      source_name: longhorn-backup-credentials-access-key
      source_type: Secret
      source_key: AWS_ACCESS_KEY_ID
---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: longhorn-backup-credentials-secret-key
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  template: |
    {{ "{{" }}  AWS_SECRET_ACCESS_KEY {{ "}}" }}
  destination_name: longhorn-backup-credentials
  destination_key: AWS_SECRET_ACCESS_KEY
  destination_type: Secret
  values:
    - name: AWS_SECRET_ACCESS_KEY
      source_name: longhorn-backup-credentials-secret-key
      source_type: Secret
      source_key: AWS_SECRET_ACCESS_KEY
---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: longhorn-backup-credentials-endpoints
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  template: |
    {{ "{{" }} AWS_ENDPOINTS {{ "}}" }}
  destination_name: longhorn-backup-credentials
  destination_key: AWS_ENDPOINTS
  destination_type: Secret
  values:
    - name: AWS_ENDPOINTS
      source_name: longhorn-backup-credentials-endpoints
      source_type: Secret
      source_key: AWS_ENDPOINTS
