---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-hourly
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  cron: "0 * * * *"
  task: "backup"
  groups:
  - hourly
  retain: 24
  concurrency: 2
  labels:
    backup: hourly
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  cron: "0 4 * * *"
  task: "backup"
  groups:
  - daily
  retain: 7
  concurrency: 2
  labels:
    backup: daily
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  cron: "0 5 * * 0"
  task: "backup"
  groups:
  - weekly
  retain: 52
  concurrency: 2
  labels:
    backup: weekly
