apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: 1.2.3
    helm:
      values: |
        persistence:
          defaultClassReplicaCount: 1
        ingress:
          enabled: true
          host: "longhorn.{{ .Values.domain}}"
          tls: true
          tlsSecret: longhorn-acme.tls
          annotations:
            cert-manager.io/cluster-issuer: acme-issuer
            nginx.ingress.kubernetes.io/auth-url: "https://longhorn.{{ .Values.domain }}/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://longhorn.{{ .Values.domain }}/oauth2/start?rd=$escaped_request_uri"
        defaultSettings:
          defaultDataLocality: "best-effort"
          backupTargetCredentialSecret: longhorn-backup-credentials
          priorityClass: high-priority
        longhornManager:
          priorityClass: high-priority
        longhornDriver:
          priorityClass: high-priority
        longhornUI:
          priorityClass: high-priority

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
