---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: longhorn-oauth2-secrets
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  templates:
    cookie-secret: '{{ "{{" }} cookie {{ "}}" }}'
    client-id: longhorn-oauth2
    client-secret: c4Pw7HREAvBewTFZ9qiTNpNDHEQGv8KL
  destination_name: oauth2-longhorn-oauth2-proxy
  destination_type: Secret
  values:
    - name: cookie
      source_name: password-oauth2-cookie-from-longhorn-system
      source_type: Secret
      source_key: password
---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: longhorn-oauth2-redis-password
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  templates:
    redis-password: '{{ "{{" }} password {{ "}}" }}'
  destination_name: oauth2-longhorn-redis
  destination_type: Secret
  values:
    - name: password
      source_name: password-oauth2-redis-from-longhorn-system
      source_type: Secret
      source_key: password
