---
include:
  - https://gitlab.home.exphost.pl/exphost/exphost-helms/-/raw/master/common/gitlab-ci.yml

stages:
  - checks
  - upload
  - deploy

nodes:
  stage: deploy
  image: alpine
  #image: bitnami/kubectl:latest
  before_script:
    - apk add --no-cache ca-certificates git curl
    - curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
    - chmod +x /usr/local/bin/kubectl
  script:
    - export VERSION=$(git describe --tags)
    - kubectl get nodes
    - kubectl patch application -n argocd exphost --patch="{\"spec\":{\"source\":{\"targetRevision\":\"${VERSION}\"}}}" --type=merge
  environment:
    name: dev
