---
include:
  - https://gitlab.exphost.pl/exphost/exphost-helms/-/raw/master/common/gitlab-ci.yml

stages:
  - checks
  - upload
  - deploy

nodes:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache ca-certificates git curl yq openssh-client-default
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB_SSH_KEY")
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.exphost.pl >> ~/.ssh/known_hosts
  script:
    - export VERSION=$(git describe --tags)
    - git clone git@gitlab.exphost.pl:exphost/exphost-config-home-lab.git config
    - cd config
    - ls
    - yq e -i ".spec.source.targetRevision=\"$VERSION\"" exphost-core.yml
    - git add exphost-core.yml
    - git commit -m "gitlab-ci update"
    - git push
  environment:
    name: dev
