---
include:
  - https://gitlab.exphost.pl/exphost/exphost-helms/-/raw/master/common/gitlab-ci.yml

stages:
  - checks
  - upload
  - deploy

deploy-to-dev:
  stage: deploy
  extends: .deploy-to-git-mainapp
  environment:
    name: dev
  variables:
    repo: git@gitlab.exphost.pl:exphost/exphost-config-home-lab.git
    yamlfile: exphost-core.yml
    waitapp: exphost
    refreshapp: cluster-config
