{
 "title": "nodes",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "pv avail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes) by (namespace, persistentvolumeclaim)"
    }
   ]
  },
  {
   "title": "Rootfs avail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (node_filesystem_avail_bytes{mountpoint=\"/\"}) by (instance, device, mountpoint)"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (node_memory_MemAvailable_bytes) by (instance)"
    }
   ]
  },
  {
   "title": "non-Rootfs avail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (node_filesystem_avail_bytes{mountpoint!=\"/\"}) by (instance, device, mountpoint)"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance)"
    }
   ]
  }
 ]
}