apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: acme-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
  - host: kube-api.{{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: kubernetes
            port:
              number: 443
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - kube-api.{{ .Values.domain }}
    secretName: api-acme.tls
