apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exphost-configurator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://gitlab.home.exphost.pl/api/v4/projects/6/packages/helm/stable'
    targetRevision: v1.1.0
    chart: exphost-configurator
    helm:
      values: |
        domain: {{ .Values.domain }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: exphost-configurator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
