apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: external-dns
    targetRevision: 6.0.2
    helm:
      values: |
        sources:
          - crd
          - ingress
          - service
        provider: coredns
        coredns:
          etcdEndpoints: "https://coredns-etcd.external-dns.svc.cluster.local:2379"
          etcdTLS:
            enabled: true
            secretName: coredns-etcd-client-root
            certFilename: tls.crt
            keyFilename: tls.key
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        logLevel: debug
        crd:
          create: true
        txtSuffix: edns
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
