apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: external-dns
    targetRevision: 5.4.6
    helm:
      values: |
        sources:
          - ingress
        provider: cloudflare
        cloudflare:
          secretName: cloudflare-token
        domainFilters:
          - {{ .Values.domain }}
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
