apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.0.4
    chart: metallb
    helm:
      values: |
        configInline:
          address-pools:
            {{ toYaml .Values.metallb.pools | nindent 12}}
        controller:
          priorityClassName: high-priority
        speaker:
          priorityClassName: high-priority

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
