apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: exphost
  source:
    repoURL: 'https://charts.helm.sh/stable'
    chart: nfs-server-provisioner
    targetRevision: 1.1.3
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: {{ .Values.persistent.nfs.size }}

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nfs-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
