apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: password-generator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitlab.home.exphost.pl/api/v4/projects/6/packages/helm/stable'
    targetRevision: v1.0.0
    chart: password-generator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: password-generator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
