apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: kube-prometheus
    targetRevision: 6.1.1
    helm:
      values: |
        prometheus:
          persistence:
            enabled: true
          ingress:
            enabled: true
            hostname: "prometheus.{{ .Values.domain }}"
            certManager: true
            tls: true
            annotations:
              cert-manager.io/cluster-issuer: acme-issuer
        node-exporter:
          tolerations:
            - key: "node-role.kubernetes.io/master"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "CriticalAddonsOnly"
              operator: "Exists"
              effect: "NoSchedule"
          extraArgs:
            collector.filesystem.ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+|run/ns/.+|run/k3s/containerd|run|var/lib/kubelet/.+)($|/)"
            path.rootfs: "/host/root"
            log.level: "debug"
          extraVolumes:
            - name: rootfs
              hostPath:
                path: /
          extraVolumeMounts:
            - name: rootfs
              mountPath: /host/root
              readOnly: true
        alertmanager:
          ingress:
            enabled: true
            hostname: "alertmanager.{{ .Values.domain }}"
            certManager: true
            tls: true
            annotations:
              cert-manager.io/cluster-issuer: acme-issuer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
