apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: template-renderer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://gitlab.exphost.pl/charts'
    targetRevision: v1.2.0
    chart: template-renderer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: template-renderer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
