apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: template-renderer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: exphost
  source:
    repoURL: 'https://gitlab.exphost.pl/charts'
    targetRevision: {{ .Values.templateRenderer.version }}
    chart: template-renderer
    helm:
      values: |
        {{- tpl (toYaml .Values.templateRenderer) . | nindent 8 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: template-renderer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
