apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://charts.dexidp.io'
    targetRevision: 0.6.5
    chart: dex
    helm:
      values: |
        configSecret:
          create: false
          name: dex-config
        ingress:
          enabled: true
          hosts:
            - host: auth.{{ .Values.domain }}
              paths:
                - path: /dex
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - auth.{{ .Values.domain }}
              secretName: dex-acme.tls
          annotations:
            cert-manager.io/cluster-issuer: acme-issuer
        priorityClassName: high-priority
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
