{{ if (and .Values.domain .Values.config.dex.ldap) }}
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: dex-connectors
  namespace: dex
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  templates:
    connectors: |
      - type: ldap
        id: ldap
        name: LDAP
        config:
          host: {{ .Values.config.dex.ldap.host }}
          insecureNoSSL: true
          bindDN: uid=dex,ou=sa,{{ include "ldap.dc" . }}
          bindPW: {{ "{{" }} dex_password {{ "}}" }}
          usernamePrompt: SSO Username
          userSearch:
            baseDN: ou=users,{{ include "ldap.dc" . }}
            filter: "(objectClass=inetOrgPerson)"
            username: cn
            idAttr: cn
            emailAttr: mail
            nameAttr: cn
          groupSearch:
            baseDN: ou=groups,{{ include "ldap.dc" . }}
            filter: "(objectClass=groupOfNames)"
            userMatchers:
              - userAttr: DN
                groupAttr: member
            nameAttr: cn
  destination_name: dex-env-configs-connectors
  destination_type: Secret
  values:
    - name: dex_password
      source_name: {{ .Values.config.dex.ldap.password.secretName }}
      source_type: Secret
      source_key: {{ .Values.config.dex.ldap.password.key }}
{{ end }}
