apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: dex-config
  namespace: dex
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  templates:
    config.yaml: |
      connectors:
      {{ "{{" }} connectors {{ "}}" }}
      storage:
        type: sqlite3
        #type: kubernetes
        config:
          file: /var/dex/dex.db
          #inCluster: true
      issuer: https://auth.{{ .Values.domain}}/dex
      staticClients:
      {{ "{{" }} clients {{ "}}" }}
  destination_name: dex-config
  destination_type: Secret
  values:
    - name: connectors
      source_name: dex-env-configs-connectors
      source_type: Secret
      source_key: connectors
    - name: clients
      source_name: dex-env-configs-staticclients
      source_type: Secret
      source_key: staticclients
