apiVersion: v1
kind: Secret
metadata:
  name: dex-env-configs-staticclients 
  namespace: dex
type: Opaque
stringData:
  staticclients: |
    {{- tpl (toYaml .Values.config.dex.staticClients) . | nindent 4 }}
