apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: dex-config
  namespace: dex
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  templates:
    config.yaml: |
      web:
        allowedOrigins: ['*']
      connectors:
      {{ "{{" }} connectors {{ "}}" }}
      storage:
        type: etcd
        config:
          endpoints:
            - http://etcd:2379
          username: root
          password: {{ "{{" }} etcdPassword {{ "}}" }}
          namespace: dex-tokens/
      issuer: https://auth.{{ .Values.domain}}/dex
      staticClients:
      {{ "{{" }} clients {{ "}}" }}
      oauth2:
        skipApprovalScreen: true
  destination_name: dex-config
  destination_type: Secret
  values:
    - name: connectors
      source_name: dex-env-configs-connectors
      source_type: Secret
      source_key: connectors
    - name: clients
      source_name: dex-env-configs-staticclients
      source_type: Secret
      source_key: staticclients
    - name: etcdPassword
      source_name: password-etcd-password-from-dex
      source_type: Secret
      source_key: password
