---
apiVersion: exphost.pl/v1
kind: Password
metadata:
  name: etcd-password
  namespace: dex
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: etcd-password
