apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-crt
  namespace: dex
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  commonName: etcd-crt
  secretName: etcd-crt
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
