apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.1.1
    chart: etcd
    helm:
      values: |
        auth:
          rbac:
            existingSecret: password-etcd-password-from-dex
            existingSecretPasswordKey: password
        persistence:
          size: 2Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
