apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://coredns.github.io/helm'
    chart: coredns
    targetRevision: 1.16.5
    helm:
      values: |
        #serviceType: LoadBalancer
        #service:
        #  annotations:
        #    metallb.universe.tf/allow-shared-ip: ingress-ip
        #    kubernetes.io/allow-mixed-protocol: "true"
        replicaCount: 3
        prometheus:
          service:
            enabled: true
          monitor:
            enabled: true
        isClusterService: false
        servers:
          - zones:
            - zone: .
            port: 53
            plugins:
            - name: errors
            - name: health
              configBlock: |-
                lameduck 5s
            - name: ready
            - name: log
              parameters: .
            - name: etcd
              parameters: dev.exphost.pl
              configBlock: |-
                stubzones
                fallthrough
                path /skydns
                endpoint https://coredns-etcd.external-dns.svc.cluster.local:2379
                tls /etc/coredns/tls/etcd/tls.crt /etc/coredns/tls/etcd/tls.key /etc/coredns/tls/etcd/ca.crt
            - name: kubernetes
              parameters: cluster.local in-addr.arpa ip6.arpa
              configBlock: |-
                pods insecure
                fallthrough in-addr.arpa ip6.arpa
                ttl 30
            - name: transfer
              parameters: dev.exphost.pl
              configBlock: |-
                to 69.65.50.192
            - name: prometheus
              parameters: 0.0.0.0:9153
            - name: cache
              parameters: 30
            - name: loop
            - name: reload
            - name: loadbalance
        extraSecrets:
          - name: coredns-etcd-client-guest
            mountPath: /etc/coredns/tls/etcd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
