---
apiVersion: v1
kind: Service
metadata:
  name: coredns-tcp-service
  namespace: external-dns
  labels:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
  annotations:
     metallb.universe.tf/allow-shared-ip: ingress-ip
     external-dns.alpha.kubernetes.io/hostname: ns1.{{ .Values.domain }}
spec:
  type: LoadBalancer
  ports:
    - name: tcp-53
      port: 53
      targetPort: 53
      protocol: TCP
  selector:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-udp-service
  namespace: external-dns
  labels:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
  annotations:
     metallb.universe.tf/allow-shared-ip: ingress-ip
     external-dns.alpha.kubernetes.io/hostname: ns1.{{ .Values.domain }}
spec:
  type: LoadBalancer
  ports:
    - name: udp-53
      port: 53
      targetPort: 53
      protocol: UDP
  selector:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
