---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dirty-etcd-secret-syncer
  namespace: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dirty-etcd-secret-syncer
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dirty-etcd-secret-syncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dirty-etcd-secret-syncer
subjects:
- kind: ServiceAccount
  name: dirty-etcd-secret-syncer
  namespace: external-dns
---
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-dirty-sync-cert-manager
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    app: dirty-syncer
spec:
  template:
    spec:
      containers:
      - name: copy-cert
        image: bitnami/kubectl
        command: ["bash"]
        args:
          - "-cx"
          - "echo { \\\"apiVersion\\\": \\\"v1\\\", \\\"kind\\\": \\\"Secret\\\", \\\"type\\\": \\\"kubernetes.io/tls\\\", \\\"metadata\\\": {\\\"name\\\": \\\"copy-of-coredns-etcd-client-root\\\", \\\"namespace\\\": \\\"cert-manager\\\"}, \\\"data\\\": $(kubectl -n external-dns get secret coredns-etcd-client-root  -o json|jq '.data')} | kubectl apply -f -"
      restartPolicy: OnFailure
      serviceAccountName: dirty-etcd-secret-syncer
