apiVersion: batch/v1
kind: Job
metadata:
  name: create-etcd-users-guest
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  namespace: external-dns
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: etcdctl
        image: docker.io/bitnami/etcd:3.5.1-debian-10-r56
        command:
          - bash
          - -c
          - |
            ETCD="etcdctl --cert=$ETCD_CERT_FILE --key=$ETCD_KEY_FILE --cacert=$ETCD_TRUSTED_CA_FILE --endpoints https://coredns-etcd.external-dns.svc.cluster.local:2379"
            $ETCD user list|grep "^guest$" || $ETCD user add guest --new-user-password=guest
        env:
          - name: ETCD_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-password-etcd-root-from-external-dns
                key: password
          - name: ETCD_TRUSTED_CA_FILE
            value: /opt/bitnami/etcd/certs/client/ca.crt
          - name: ETCD_CERT_FILE
            value: /opt/bitnami/etcd/certs/client/tls.crt
          - name: ETCD_KEY_FILE
            value: /opt/bitnami/etcd/certs/client/tls.key
        volumeMounts:
          - mountPath: /opt/bitnami/etcd/certs/client/
            name: etcd-client-certs
            readOnly: true
      volumes:
        - name: etcd-client-certs
          secret:
            secretName: coredns-etcd-client-root
