apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-etcd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: etcd
    targetRevision: 6.11.0
    helm:
      values: |
        metrics:
          enabled: true
          podMonitor:
            enabled: true
            namespace: external-dns
        auth:
          rbac:
            existingSecret: password-password-etcd-root-from-external-dns
            existingSecretPasswordKey: password
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
