apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-etcd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: etcd
    targetRevision: 6.11.0
    helm:
      values: |
        metrics:
          enabled: true
          podMonitor:
            enabled: true
            namespace: external-dns
            scheme: https
            tlsConfig:
              ca:
                secret:
                  name: coredns-etcd-client-guest
                  key: ca.crt
              cert:
                secret:
                  name: coredns-etcd-client-guest
                  key: tls.crt
              keySecret:
                name: coredns-etcd-client-guest
                key: tls.key
              serverName: coredns-etcd.external-dns
        auth:
          rbac:
            existingSecret: password-password-etcd-root-from-external-dns
            existingSecretPasswordKey: password
          client:
            secureTransport: true
            existingSecret: coredns-etcd-client-cert
            enableAuthentication: true
            certFilename: tls.crt
            certKeyFilename: tls.key
            caFilename: ca.crt
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
