apiVersion: batch/v1
kind: Job
metadata:
  name: create-etcd-roles-guest
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  namespace: external-dns
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: etcdctl
        image: docker.io/bitnami/etcd:3.5.1-debian-10-r56
        command:
          - bash
          - -c
          - |
            ETCD="etcdctl --user root --password $ETCD_ROOT_PASSWORD --endpoints http://coredns-etcd.external-dns.svc.cluster.local:2379"
            role=$($ETCD role list|grep "^guest$")
            if [ -z "$role" ]; then
              echo "granting permissions"
              $ETCD role add guest 
              $ETCD role grant-permission guest read ""
            fi
        env:
          - name: ETCD_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-password-etcd-root-from-external-dns
                key: password
