apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules-pods
  namespace: prometheus-system
  labels:
    prometheus: example
    role: alert-rules
spec:
  groups:
  - name: ./pods.rules
    rules:
    - alert: non schedulable pods
      expr: kube_pod_status_phase{phase!="Running",phase!="Succeeded"} >0
