apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules-pods
  namespace: prometheus-system
  labels:
    prometheus: example
    role: alert-rules
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  groups:
  - name: ./pods.rules
    rules:
    - alert: non schedulable pods
      expr: kube_pod_status_phase{phase!="Running",phase!="Succeeded"} >0
      for: 1m
    - alert: crashing pods
      expr: (kube_pod_status_ready{condition!='true', exported_pod !~"rke2-coredns-rke2-coredns.*" } >0) * on (exported_pod) group_left(container) (kube_pod_status_phase{phase="Running"} >0)
      for: 1m
