apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules-up
  namespace: prometheus-system
  labels:
    prometheus: example
    role: alert-rules
spec:
  groups:
  - name: ./up.rules
    rules:
    - alert: targets up
      expr: up == 0
