apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
spec:
  project: exphost
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: external-dns
    targetRevision: 6.1.4
    helm:
      values: |
        sources:
          - crd
          - ingress
          - service
        provider: rfc2136
        domainFilters:
          - {{ .Values.domain }}
        rfc2136:
          host: named-mixed.named.svc.cluster.local.
          zone: "{{ .Values.domain }}"
          secretName: rfc2136-tsig-secret
          tsigKeyname: external-dns-key
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        logLevel: debug
        crd:
          create: true
        txtSuffix: -extdns
        policy: sync
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
