apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: acme-home@fabrykowski.pl
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
    - dns01:
        rfc2136:
          nameserver: named-mixed.named.svc.cluster.local.
          tsigKeyName: cert-manager-key
          tsigAlgorithm: HMACSHA256
          tsigSecretSecretRef:
            name: password-cert-manager-key-from-named
            key: base64
