apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: exphost
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 7.2.12
    chart: grafana
    helm:
      values: |
        ingress:
          enabled: true
          hostname: grafana.{{ .Values.domain }}
          certManager: true
          annotations:
            cert-manager.io/cluster-issuer: acme-issuer
          tls: true

        replicaCount: 1
        datasources:
          secretName: grafana-datasources
        dashboardsConfigMaps:
          {{- range $path, $_ := .Files.Glob "files/grafana/dashboards/*" }}
            - configMapName: grafana-dashboards-{{ $path | base | replace "_" "-" | lower | replace ".json" "" }}
              fileName: {{ $path | base | replace "_" "-" | lower}}
          {{- end }}
        #  - configMapName: grafana-dashboards-nodes
        #    fileName: nodes.json
        #  - configMapName: grafana-dashboards-general-view
        #    fileName: general-view.json
        #  - configMapName: grafana-dashboards-argocd
        #    fileName: argocd.json
        dashboardsProvider:
          enabled: true
        #ldap:
        #  enabled: true
        #  configMapName: ldap-config
        #  allowSignUp: true
        persistence:
          enabled: true
          accessMode: ReadWriteMany
        config:
          useGrafanaIniFile: true
          grafanaIniConfigMap: grafana-config


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
