apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana
data:
  grafana.ini: |
    [server]
    root_url = https://grafana.{{ .Values.domain }}
    
    [session]
    cookie_secure = true
    [auth.generic_oauth]
    enabled = true
    client_id = grafana
    client_secret = yipcAxlvSLPFgpU+FN+SynW5fAbSQqeG2zTJ/4ioTKU=
    scopes = openid profile email groups
    empty_scopes = false
    auth_url = https://auth.dev.exphost.pl/dex/auth
    token_url = https://auth.dev.exphost.pl/dex/token
    api_url = https://auth.dev.exphost.pl/dex/userinfo
    redirect_url = https://grafana.dev.exphost.pl/login/generic_oauth
    #allowed_domains = mycompany.com mycompany.org
    allow_sign_up = true
    tls_skip_verify_insecure = false
